### ISSUE TITLE
code block adaptation issue

### ISSUE THREAD

**Issue by shpdnkti** [YeungKC/Hakuba#115]
**Describe the bug**

There is a problem with the code block adaptation，i built it by cloudflare page.
Maybe not support escape character or other reasons. pls help me find out how to fix it.

- error stack：
```
21:57:17.717	> Using @sveltejs/adapter-static
21:57:17.717	[vite-plugin-svelte-kit] Cannot read properties of undefined (reading 'paths')
21:57:17.717	error during build:
21:57:17.717	TypeError: Cannot read properties of undefined (reading 'paths')
21:57:17.718	    at create_builder (file:///opt/buildhome/repo/node_modules/@sveltejs/kit/dist/chunks/index2.js:52:48)
21:57:17.718	    at adapt (file:///opt/buildhome/repo/node_modules/@sveltejs/kit/dist/chunks/index2.js:204:18)
21:57:17.718	    at Object.closeBundle (file:///opt/buildhome/repo/node_modules/@sveltejs/kit/dist/vite.js:3104:11)
21:57:17.718	    at async Promise.all (index 0)
21:57:17.718	    at async /opt/buildhome/repo/node_modules/rollup/dist/shared/rollup.js:23693:13
21:57:17.718	    at async catchUnfinishedHookActions (/opt/buildhome/repo/node_modules/rollup/dist/shared/rollup.js:23174:20)
21:57:17.718	    at async rollupInternal (/opt/buildhome/repo/node_modules/rollup/dist/shared/rollup.js:23682:5)
21:57:17.719	    at async doBuild (/opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:41710:24)
21:57:17.719	    at async build (/opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:41552:16)
21:57:17.719	    at async CAC.<anonymous> (/opt/buildhome/repo/node_modules/vite/dist/node/cli.js:738:9)
21:57:17.744	error Command failed with exit code 1.
21:57:17.744	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
21:57:17.758	Failed: build command exited with code: 1
21:57:18.586	Failed: an internal error occurred
```

- original code block content

```
````bash
ok () { echo -e "[\033[032;1mOK\033[0m $(date +%F/%T) $BASH_LINENO] $@" | tee -a $LOG_FILE 2>&1; return 0; }
info () { echo -e "[\033[034;1mINFO\033[0m $(date +%F/%T) $BASH_LINENO] $@" | tee -a $LOG_FILE 2>&1; return $?; }
fail () { echo -e "[\033[031;1mFAIL\033[0m $(date +%F/%T) $BASH_LINENO] $@" | tee -a $LOG_FILE 2>&1; return $?; }
err () { echo -e "[\033[031;1mERR\033[0m $(date +%F/%T) $BASH_LINENO] $@" | tee -a $LOG_FILE 2>&1; exit 1; }
....
```

**Comment by YeungKC** [comment]
I test the code block content, I think it was cause by Mdsvex, I'll test it over the weekend again.
